# Generated by Django 2.2.1 on 2019-05-15 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190515_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.CharField(max_length=30, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='heroage',
            field=models.IntegerField(max_length=5, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='heroname',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hgender',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='nbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='所属丛书'),
        ),
    ]
