# Generated by Django 2.2.1 on 2019-05-18 03:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190517_1618'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('c', django.db.models.manager.Manager()),
            ],
        ),
    ]
