# Generated by Django 2.2.1 on 2019-05-23 09:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190523_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('emal', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=30)),
                ('txt', tinymce.models.HTMLField()),
            ],
        ),
    ]
