# Generated by Django 2.2.1 on 2019-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='absimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='abs', verbose_name='图片文件')),
                ('msg', models.CharField(max_length=20, verbose_name='消息')),
            ],
            options={
                'verbose_name': '轮播',
                'verbose_name_plural': '轮播',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='emal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=30, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
