# Generated by Django 2.2.1 on 2019-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20190523_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
    ]
