# Generated by Django 2.2.1 on 2019-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='choice',
            field=models.CharField(max_length=20, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='list',
            name='num',
            field=models.IntegerField(verbose_name='票数'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
