# Generated by Django 2.2.1 on 2019-05-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190518_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='list',
            name='num',
        ),
        migrations.CreateModel(
            name='listcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=20, verbose_name='选项')),
                ('num', models.IntegerField(verbose_name='票数')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.list', verbose_name='标题')),
            ],
        ),
    ]
