# Generated by Django 2.2.1 on 2019-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
                ('sign', models.CharField(choices=[('1', '用户'), ('2', '管理员')], default=1, max_length=10, verbose_name='标识')),
            ],
        ),
    ]
